apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authz-check-acp-claim-customerid-lua
  namespace: default
spec:
  workloadSelector:
    labels:
      app: istio-demo-wrapper
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)
                 request_handle:respond(
                 {[":status"] = "200",
                 },
                 "Response from lua filter")
            end

            function envoy_on_response(response_handle)
                  response_handle:respond("Goodbye.")
            end